CREATE TABLE player
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(50),
    birth_date          DATE,
    offensive_function  VARCHAR(11),
    zone_function       VARCHAR(11),
    uniform_number      INTEGER,
    nicknames           VARCHAR(255),
    gender              VARCHAR(10),
    join_date           DATE,
    CONSTRAINT pk_player PRIMARY KEY (id)
);

CREATE TABLE team_player
(
    team_id    BIGINT NOT NULL,
    player_id  BIGINT NOT NULL,
    CONSTRAINT pk_team_player PRIMARY KEY (team_id, player_id)
);

ALTER TABLE team_player ADD CONSTRAINT fk_tea_on_player FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE team_player ADD CONSTRAINT fk_tea_on_team FOREIGN KEY (team_id) REFERENCES team (id);