CREATE TABLE training
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date                DATE NOT NULL,
    start_time          TIME WITHOUT TIME ZONE,
    duration_minutes    INTEGER,
    location            VARCHAR(255),
    description         TEXT,
    team_id             BIGINT NOT NULL,
    CONSTRAINT pk_training PRIMARY KEY (id),
    CONSTRAINT fk_training_on_team FOREIGN KEY (team_id) REFERENCES team (id)
);