CREATE TABLE attendance
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id           BIGINT NOT NULL,
    training_id         BIGINT NOT NULL,
    status              VARCHAR(20) NOT NULL,
    registration_date   TIMESTAMP WITHOUT TIME ZONE,
    justification       TEXT,
    CONSTRAINT pk_attendance PRIMARY KEY (id),
    CONSTRAINT fk_att_on_player FOREIGN KEY (player_id) REFERENCES player (id),
    CONSTRAINT fk_att_on_training FOREIGN KEY (training_id) REFERENCES training (id),
    CONSTRAINT uk_attendance_player_training UNIQUE (player_id, training_id)
);